### ISSUE TITLE
EloByWeekday failing on nonexistent saturday games

### ISSUE THREAD

**Issue by guidopetri** [guidopetri/chess-pipeline#1]
When there are no games in the last day of the week (currently saturday), EloByWeekday fails with the following error message:

```
Runtime error:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/home/pi/.local/lib/python3.7/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/pi/Git/chess-pipeline/newsletter.py", line 254, in run
    bbox_inches='tight')
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2065, in print_figure
    **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 527, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/text.py", line 2355, in draw
    xy_pixel = self._get_position_xy(renderer)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/text.py", line 1905, in _get_position_xy
    return self._get_xy(renderer, x, y, self.xycoords)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/text.py", line 1761, in _get_xy
    y = float(self.convert_yunits(y))
TypeError: only size-1 arrays can be converted to Python scalars
```

This doesn't necessarily happen in line 254. Running the function piecewise in an interpreter seems to bring this error up earlier.

**Comment by guidopetri** [comment]
Tentatively closed by commit 1590666 .
