### ISSUE TITLE
WinRatioByColor fails when no games exist

### ISSUE THREAD

**Issue by guidopetri** [guidopetri/chess-pipeline#2]
If no games exist for the week, WinRatioByColor fails:

```
Runtime error:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/home/pi/.local/lib/python3.7/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/pi/Git/chess-pipeline/newsletter.py", line 113, in run
    1.01],  # enforce two digits of precision
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/plotting/_core.py", line 847, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/plotting/_matplotlib/__init__.py", line 61, in plot
    plot_obj.generate()
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py", line 265, in generate
    self._make_legend()
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py", line 572, in _make_legend
    ax.legend(handles, labels, loc="best", title=title)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 406, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/legend.py", line 575, in __init__
    self._init_legend_box(handles, labels, markerfirst)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/legend.py", line 833, in _init_legend_box
    fontsize, handlebox))
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/legend_handler.py", line 115, in legend_artist
    fontsize, handlebox.get_transform())
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/legend_handler.py", line 299, in create_artists
    self.update_prop(p, orig_handle, legend)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/legend_handler.py", line 72, in update_prop
    self._update_prop(legend_handle, orig_handle)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/legend_handler.py", line 65, in _update_prop
    self._update_prop_func(legend_handle, orig_handle)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/legend_handler.py", line 38, in update_from_first_child
    tgt.update_from(src.get_children()[0])
IndexError: list index out of range
```

**Comment by guidopetri** [comment]
Tentatively closed by ba7929a.
